"""Auto-generated place names (Division/District/Tehsil, Urdu+English).
Regenerated from punjab_divisions.py — do not hand-edit."""

PLACE_NAMES = {
    "ur": {
        "all_divisions": "تمام ڈویژنز",
        "browse_divisions": "ڈویژنز دیکھیں",
        "dist_attock": "اٹک",
        "dist_attock_seo": "اٹک میں کرائے کے مکانات",
        "dist_bahawalnagar": "بہاولنگر",
        "dist_bahawalnagar_seo": "بہاولنگر میں کرائے کے مکانات",
        "dist_bahawalpur": "بہاولپور",
        "dist_bahawalpur_seo": "بہاولپور میں کرائے کے مکانات",
        "dist_bhakkar": "بھکر",
        "dist_bhakkar_seo": "بھکر میں کرائے کے مکانات",
        "dist_chakwal": "چکوال",
        "dist_chakwal_seo": "چکوال میں کرائے کے مکانات",
        "dist_chiniot": "چنیوٹ",
        "dist_chiniot_seo": "چنیوٹ میں کرائے کے مکانات",
        "dist_dera-ghazi-khan": "ڈیرہ غازی خان",
        "dist_dera-ghazi-khan_seo": "ڈیرہ غازی خان میں کرائے کے مکانات",
        "dist_faisalabad": "فیصل آباد",
        "dist_faisalabad_seo": "فیصل آباد میں کرائے کے مکانات",
        "dist_gujranwala": "گوجرانوالہ",
        "dist_gujranwala_seo": "گوجرانوالہ میں کرائے کے مکانات",
        "dist_gujrat": "گجرات",
        "dist_gujrat_seo": "گجرات میں کرائے کے مکانات",
        "dist_hafizabad": "حافظ آباد",
        "dist_hafizabad_seo": "حافظ آباد میں کرائے کے مکانات",
        "dist_jhang": "جھنگ",
        "dist_jhang_seo": "جھنگ میں کرائے کے مکانات",
        "dist_jhelum": "جہلم",
        "dist_jhelum_seo": "جہلم میں کرائے کے مکانات",
        "dist_kasur": "قصور",
        "dist_kasur_seo": "قصور میں کرائے کے مکانات",
        "dist_khanewal": "خانیوال",
        "dist_khanewal_seo": "خانیوال میں کرائے کے مکانات",
        "dist_khushab": "خوشاب",
        "dist_khushab_seo": "خوشاب میں کرائے کے مکانات",
        "dist_kot-addu": "کوٹ ادو",
        "dist_kot-addu_seo": "کوٹ ادو میں کرائے کے مکانات",
        "dist_lahore": "لاہور",
        "dist_lahore_seo": "لاہور میں کرائے کے مکانات",
        "dist_layyah": "لیہ",
        "dist_layyah_seo": "لیہ میں کرائے کے مکانات",
        "dist_lodhran": "لودھراں",
        "dist_lodhran_seo": "لودھراں میں کرائے کے مکانات",
        "dist_mandi-bahauddin": "منڈی بہاؤالدین",
        "dist_mandi-bahauddin_seo": "منڈی بہاؤالدین میں کرائے کے مکانات",
        "dist_mianwali": "میانوالی",
        "dist_mianwali_seo": "میانوالی میں کرائے کے مکانات",
        "dist_multan": "ملتان",
        "dist_multan_seo": "ملتان میں کرائے کے مکانات",
        "dist_murree": "مری",
        "dist_murree_seo": "مری میں کرائے کے مکانات",
        "dist_muzaffargarh": "مظفرگڑھ",
        "dist_muzaffargarh_seo": "مظفرگڑھ میں کرائے کے مکانات",
        "dist_nankana-sahib": "ننکانہ صاحب",
        "dist_nankana-sahib_seo": "ننکانہ صاحب میں کرائے کے مکانات",
        "dist_narowal": "نارووال",
        "dist_narowal_seo": "نارووال میں کرائے کے مکانات",
        "dist_okara": "اوکاڑہ",
        "dist_okara_seo": "اوکاڑہ میں کرائے کے مکانات",
        "dist_pakpattan": "پاکپتن",
        "dist_pakpattan_seo": "پاکپتن میں کرائے کے مکانات",
        "dist_rahim-yar-khan": "رحیم یار خان",
        "dist_rahim-yar-khan_seo": "رحیم یار خان میں کرائے کے مکانات",
        "dist_rajanpur": "راجن پور",
        "dist_rajanpur_seo": "راجن پور میں کرائے کے مکانات",
        "dist_rawalpindi": "راولپنڈی",
        "dist_rawalpindi_seo": "راولپنڈی میں کرائے کے مکانات",
        "dist_sahiwal": "ساہیوال",
        "dist_sahiwal_seo": "ساہیوال میں کرائے کے مکانات",
        "dist_sargodha": "سرگودھا",
        "dist_sargodha_seo": "سرگودھا میں کرائے کے مکانات",
        "dist_sheikhupura": "شیخوپورہ",
        "dist_sheikhupura_seo": "شیخوپورہ میں کرائے کے مکانات",
        "dist_sialkot": "سیالکوٹ",
        "dist_sialkot_seo": "سیالکوٹ میں کرائے کے مکانات",
        "dist_talagang": "تلہ گنگ",
        "dist_talagang_seo": "تلہ گنگ میں کرائے کے مکانات",
        "dist_taunsa": "تونسہ",
        "dist_taunsa_seo": "تونسہ میں کرائے کے مکانات",
        "dist_toba-tek-singh": "ٹوبہ ٹیک سنگھ",
        "dist_toba-tek-singh_seo": "ٹوبہ ٹیک سنگھ میں کرائے کے مکانات",
        "dist_vehari": "وہاڑی",
        "dist_vehari_seo": "وہاڑی میں کرائے کے مکانات",
        "dist_wazirabad": "وزیر آباد",
        "dist_wazirabad_seo": "وزیر آباد میں کرائے کے مکانات",
        "district": "ضلع",
        "div_bahawalpur": "بہاولپور",
        "div_bahawalpur_seo": "بہاولپور میں کرائے کے مکانات",
        "div_dera-ghazi-khan": "ڈیرہ غازی خان",
        "div_dera-ghazi-khan_seo": "ڈیرہ غازی خان میں کرائے کے مکانات",
        "div_faisalabad": "فیصل آباد",
        "div_faisalabad_seo": "فیصل آباد میں کرائے کے مکانات",
        "div_gujranwala": "گوجرانوالہ",
        "div_gujranwala_seo": "گوجرانوالہ میں کرائے کے مکانات",
        "div_gujrat": "گجرات",
        "div_gujrat_seo": "گجرات میں کرائے کے مکانات",
        "div_lahore": "لاہور",
        "div_lahore_seo": "لاہور میں کرائے کے مکانات",
        "div_multan": "ملتان",
        "div_multan_seo": "ملتان میں کرائے کے مکانات",
        "div_rawalpindi": "راولپنڈی",
        "div_rawalpindi_seo": "راولپنڈی میں کرائے کے مکانات",
        "div_sahiwal": "ساہیوال",
        "div_sahiwal_seo": "ساہیوال میں کرائے کے مکانات",
        "div_sargodha": "سرگودھا",
        "div_sargodha_seo": "سرگودھا میں کرائے کے مکانات",
        "division": "ڈویژن",
        "divisions_title": "ڈویژن منتخب کریں",
        "filter_district": "ضلع",
        "filter_division": "ڈویژن",
        "filter_tehsil": "تحصیل",
        "select_district": "ضلع منتخب کریں",
        "select_division": "ڈویژن منتخب کریں",
        "select_tehsil": "تحصیل منتخب کریں",
        "teh_ahmadpur-east": "احمد پور شرقیہ",
        "teh_ahmadpur-sial": "احمد پور سیال",
        "teh_ali-pur-chatta": "علی پور چٹھہ",
        "teh_alipur": "علی پور",
        "teh_arifwala": "عارف والا",
        "teh_athara-hazari": "اٹھارہ ہزاری",
        "teh_attock": "اٹک",
        "teh_bahawalnagar": "بہاولنگر",
        "teh_bahawalpur-city": "بہاولپور شہر",
        "teh_bahawalpur-saddar": "بہاولپور صدر",
        "teh_bhakkar": "بھکر",
        "teh_bhalwal": "بھلوال",
        "teh_bhera": "بھیرہ",
        "teh_bhuwana": "بھوانہ",
        "teh_burewala": "بورے والا",
        "teh_chak-jhumra": "چک جھمرہ",
        "teh_chakwal": "چکوال",
        "teh_chaubara": "چوبارہ",
        "teh_chichawatni": "چیچہ وطنی",
        "teh_chiniot": "چنیوٹ",
        "teh_chishtian": "چشتیاں",
        "teh_choa-saidan-shah": "چوآ سیدن شاہ",
        "teh_chowk-sarwar-shaheed": "چوک سرور شہید",
        "teh_chunian": "چونیاں",
        "teh_darya-khan": "دریا خان",
        "teh_daska": "ڈسکہ",
        "teh_daultala": "دولتالہ",
        "teh_de-excluded-area-rajanpur": "ڈی ایکسکلوڈڈ ایریا راجن پور",
        "teh_depalpur": "دیپالپور",
        "teh_dera-ghazi-khan": "ڈیرہ غازی خان",
        "teh_dina": "دینہ",
        "teh_dunyapur": "دنیا پور",
        "teh_faisalabad-city": "فیصل آباد شہر",
        "teh_faisalabad-saddar": "فیصل آباد صدر",
        "teh_fateh-jang": "فتح جنگ",
        "teh_ferozewala": "فیروزوالہ",
        "teh_fort-abbas": "فورٹ عباس",
        "teh_gojra": "گوجرہ",
        "teh_gujar-khan": "گوجر خان",
        "teh_gujranwala-city": "گوجرانوالہ شہر",
        "teh_gujranwala-saddar": "گوجرانوالہ صدر",
        "teh_gujrat": "گجرات",
        "teh_hafizabad": "حافظ آباد",
        "teh_haroonabad": "ہارون آباد",
        "teh_hasilpur": "حاصل پور",
        "teh_hassan-abdal": "حسن ابدال",
        "teh_hazro": "حضرو",
        "teh_isakhel": "عیسیٰ خیل",
        "teh_jahanian": "جہانیاں",
        "teh_jalalpur-jattan": "جلالپور جٹاں",
        "teh_jalalpur-pirwala": "جلالپور پیروالہ",
        "teh_jallah-jeem": "جلہ جیم",
        "teh_jand": "جنڈ",
        "teh_jaranwala": "جڑانوالہ",
        "teh_jatoi": "جتوئی",
        "teh_jhang": "جھنگ",
        "teh_jhelum": "جہلم",
        "teh_kabirwala": "کبیروالا",
        "teh_kahror-pacca": "کہروڑ پکا",
        "teh_kahuta": "کہوٹہ",
        "teh_kallar-kahar": "کلر کہار",
        "teh_kallar-syedan": "کلر سیداں",
        "teh_kaloorkot": "کلورکوٹ",
        "teh_kamalia": "کمالیہ",
        "teh_kamoke": "کامونکی",
        "teh_karor-lal-esan": "کروڑ لعل عیسن",
        "teh_kasur": "قصور",
        "teh_khairpur-tamewali": "خیر پور ٹامیوالی",
        "teh_khanewal": "خانیوال",
        "teh_khanpur": "خان پور",
        "teh_kharian": "کھاریاں",
        "teh_khushab": "خوشاب",
        "teh_koh-e-suleman": "کوہ سلیمان",
        "teh_kot-addu": "کوٹ ادو",
        "teh_kot-chutta": "کوٹ چھٹہ",
        "teh_kot-momin": "کوٹ مومن",
        "teh_kot-radha-kishan": "کوٹ رادھا کشن",
        "teh_kotli-sattian": "کوٹلی ستیاں",
        "teh_kunjah": "کنجاہ",
        "teh_lahore-cantt": "لاہور کینٹ",
        "teh_lahore-city": "لاہور شہر",
        "teh_lalian": "لالیاں",
        "teh_lawa": "لاوہ",
        "teh_layyah": "لیہ",
        "teh_liaqatpur": "لیاقت پور",
        "teh_lodhran": "لودھراں",
        "teh_mailsi": "میلسی",
        "teh_malakwal": "ملکوال",
        "teh_mandi-bahauddin": "منڈی بہاؤالدین",
        "teh_mandi-shah-jeewna": "منڈی شاہ جیونا",
        "teh_mankera": "منکیرہ",
        "teh_mian-channu": "میاں چنوں",
        "teh_mianwali": "میانوالی",
        "teh_minchinabad": "منچن آباد",
        "teh_model-town": "ماڈل ٹاؤن",
        "teh_multan-city": "ملتان شہر",
        "teh_multan-khurd": "ملتان خورد",
        "teh_multan-saddar": "ملتان صدر",
        "teh_muridke": "مریدکے",
        "teh_murree": "مری",
        "teh_muzaffargarh": "مظفرگڑھ",
        "teh_nankana-sahib": "ننکانہ صاحب",
        "teh_narowal": "نارووال",
        "teh_naushera": "نوشہرہ (وادی سون)",
        "teh_noorpur-thal": "نور پور تھل",
        "teh_nowshera-virkan": "نوشہرہ ورکاں",
        "teh_okara": "اوکاڑہ",
        "teh_pakpattan": "پاکپتن",
        "teh_pasrur": "پسرور",
        "teh_pattoki": "پتوکی",
        "teh_phalia": "پھالیہ",
        "teh_pind-dadan-khan": "پنڈ دادن خان",
        "teh_pindi-bhattian": "پنڈی بھٹیاں",
        "teh_pindi-gheb": "پنڈی گھیب",
        "teh_piplan": "پپلاں",
        "teh_pirmahal": "پیر محل",
        "teh_quaidabad": "قائد آباد",
        "teh_rahim-yar-khan": "رحیم یار خان",
        "teh_raiwind": "رائیونڈ",
        "teh_rajanpur": "راجن پور",
        "teh_rawalpindi": "راولپنڈی",
        "teh_renala-khurd": "رینالہ خورد",
        "teh_rojhan": "روجھان",
        "teh_sadiqabad": "صادق آباد",
        "teh_safdarabad": "صفدرآباد",
        "teh_sahiwal": "ساہیوال",
        "teh_sambrial": "سمبڑیال",
        "teh_samundri": "سمندری",
        "teh_sangla-hill": "سانگلہ ہل",
        "teh_sarai-alamgir": "سرائے عالمگیر",
        "teh_sargodha": "سرگودھا",
        "teh_shah-kot": "شاہ کوٹ",
        "teh_shahpur": "شاہ پور",
        "teh_shakargarh": "شکر گڑھ",
        "teh_shalimar": "شالیمار",
        "teh_sharaqpur": "شرق پور",
        "teh_sheikhupura": "شیخوپورہ",
        "teh_shorkot": "شورکوٹ",
        "teh_shujabad": "شجاع آباد",
        "teh_sialkot": "سیالکوٹ",
        "teh_sillanwali": "سلانوالی",
        "teh_sohawa": "سوہاوہ",
        "teh_talagang": "تلہ گنگ",
        "teh_tandlianwala": "تاندلیانوالہ",
        "teh_taunsa": "تونسہ",
        "teh_taxila": "ٹیکسلا",
        "teh_toba-tek-singh": "ٹوبہ ٹیک سنگھ",
        "teh_vehari": "وہاڑی",
        "teh_wahova": "وہوا",
        "teh_wazirabad": "وزیر آباد",
        "teh_yazman": "یزمان",
        "teh_zafarwal": "ظفر وال",
        "tehsil": "تحصیل",
    },
    "en": {
        "all_divisions": "All divisions",
        "browse_divisions": "Browse divisions",
        "dist_attock": "Attock",
        "dist_attock_seo": "Houses for rent in Attock",
        "dist_bahawalnagar": "Bahawalnagar",
        "dist_bahawalnagar_seo": "Houses for rent in Bahawalnagar",
        "dist_bahawalpur": "Bahawalpur",
        "dist_bahawalpur_seo": "Houses for rent in Bahawalpur",
        "dist_bhakkar": "Bhakkar",
        "dist_bhakkar_seo": "Houses for rent in Bhakkar",
        "dist_chakwal": "Chakwal",
        "dist_chakwal_seo": "Houses for rent in Chakwal",
        "dist_chiniot": "Chiniot",
        "dist_chiniot_seo": "Houses for rent in Chiniot",
        "dist_dera-ghazi-khan": "Dera Ghazi Khan",
        "dist_dera-ghazi-khan_seo": "Houses for rent in Dera Ghazi Khan",
        "dist_faisalabad": "Faisalabad",
        "dist_faisalabad_seo": "Houses for rent in Faisalabad",
        "dist_gujranwala": "Gujranwala",
        "dist_gujranwala_seo": "Houses for rent in Gujranwala",
        "dist_gujrat": "Gujrat",
        "dist_gujrat_seo": "Houses for rent in Gujrat",
        "dist_hafizabad": "Hafizabad",
        "dist_hafizabad_seo": "Houses for rent in Hafizabad",
        "dist_jhang": "Jhang",
        "dist_jhang_seo": "Houses for rent in Jhang",
        "dist_jhelum": "Jhelum",
        "dist_jhelum_seo": "Houses for rent in Jhelum",
        "dist_kasur": "Kasur",
        "dist_kasur_seo": "Houses for rent in Kasur",
        "dist_khanewal": "Khanewal",
        "dist_khanewal_seo": "Houses for rent in Khanewal",
        "dist_khushab": "Khushab",
        "dist_khushab_seo": "Houses for rent in Khushab",
        "dist_kot-addu": "Kot Addu",
        "dist_kot-addu_seo": "Houses for rent in Kot Addu",
        "dist_lahore": "Lahore",
        "dist_lahore_seo": "Houses for rent in Lahore",
        "dist_layyah": "Layyah",
        "dist_layyah_seo": "Houses for rent in Layyah",
        "dist_lodhran": "Lodhran",
        "dist_lodhran_seo": "Houses for rent in Lodhran",
        "dist_mandi-bahauddin": "Mandi Bahauddin",
        "dist_mandi-bahauddin_seo": "Houses for rent in Mandi Bahauddin",
        "dist_mianwali": "Mianwali",
        "dist_mianwali_seo": "Houses for rent in Mianwali",
        "dist_multan": "Multan",
        "dist_multan_seo": "Houses for rent in Multan",
        "dist_murree": "Murree",
        "dist_murree_seo": "Houses for rent in Murree",
        "dist_muzaffargarh": "Muzaffargarh",
        "dist_muzaffargarh_seo": "Houses for rent in Muzaffargarh",
        "dist_nankana-sahib": "Nankana Sahib",
        "dist_nankana-sahib_seo": "Houses for rent in Nankana Sahib",
        "dist_narowal": "Narowal",
        "dist_narowal_seo": "Houses for rent in Narowal",
        "dist_okara": "Okara",
        "dist_okara_seo": "Houses for rent in Okara",
        "dist_pakpattan": "Pakpattan",
        "dist_pakpattan_seo": "Houses for rent in Pakpattan",
        "dist_rahim-yar-khan": "Rahim Yar Khan",
        "dist_rahim-yar-khan_seo": "Houses for rent in Rahim Yar Khan",
        "dist_rajanpur": "Rajanpur",
        "dist_rajanpur_seo": "Houses for rent in Rajanpur",
        "dist_rawalpindi": "Rawalpindi",
        "dist_rawalpindi_seo": "Houses for rent in Rawalpindi",
        "dist_sahiwal": "Sahiwal",
        "dist_sahiwal_seo": "Houses for rent in Sahiwal",
        "dist_sargodha": "Sargodha",
        "dist_sargodha_seo": "Houses for rent in Sargodha",
        "dist_sheikhupura": "Sheikhupura",
        "dist_sheikhupura_seo": "Houses for rent in Sheikhupura",
        "dist_sialkot": "Sialkot",
        "dist_sialkot_seo": "Houses for rent in Sialkot",
        "dist_talagang": "Talagang",
        "dist_talagang_seo": "Houses for rent in Talagang",
        "dist_taunsa": "Taunsa",
        "dist_taunsa_seo": "Houses for rent in Taunsa",
        "dist_toba-tek-singh": "Toba Tek Singh",
        "dist_toba-tek-singh_seo": "Houses for rent in Toba Tek Singh",
        "dist_vehari": "Vehari",
        "dist_vehari_seo": "Houses for rent in Vehari",
        "dist_wazirabad": "Wazirabad",
        "dist_wazirabad_seo": "Houses for rent in Wazirabad",
        "district": "District",
        "div_bahawalpur": "Bahawalpur",
        "div_bahawalpur_seo": "Houses for rent in Bahawalpur Division",
        "div_dera-ghazi-khan": "Dera Ghazi Khan",
        "div_dera-ghazi-khan_seo": "Houses for rent in Dera Ghazi Khan Division",
        "div_faisalabad": "Faisalabad",
        "div_faisalabad_seo": "Houses for rent in Faisalabad Division",
        "div_gujranwala": "Gujranwala",
        "div_gujranwala_seo": "Houses for rent in Gujranwala Division",
        "div_gujrat": "Gujrat",
        "div_gujrat_seo": "Houses for rent in Gujrat Division",
        "div_lahore": "Lahore",
        "div_lahore_seo": "Houses for rent in Lahore Division",
        "div_multan": "Multan",
        "div_multan_seo": "Houses for rent in Multan Division",
        "div_rawalpindi": "Rawalpindi",
        "div_rawalpindi_seo": "Houses for rent in Rawalpindi Division",
        "div_sahiwal": "Sahiwal",
        "div_sahiwal_seo": "Houses for rent in Sahiwal Division",
        "div_sargodha": "Sargodha",
        "div_sargodha_seo": "Houses for rent in Sargodha Division",
        "division": "Division",
        "divisions_title": "Choose a division",
        "filter_district": "District",
        "filter_division": "Division",
        "filter_tehsil": "Tehsil",
        "select_district": "Select district",
        "select_division": "Select division",
        "select_tehsil": "Select tehsil",
        "teh_ahmadpur-east": "Ahmadpur East",
        "teh_ahmadpur-sial": "Ahmadpur Sial",
        "teh_ali-pur-chatta": "Ali Pur Chatta",
        "teh_alipur": "Alipur",
        "teh_arifwala": "Arifwala",
        "teh_athara-hazari": "Athara Hazari",
        "teh_attock": "Attock",
        "teh_bahawalnagar": "Bahawalnagar",
        "teh_bahawalpur-city": "Bahawalpur City",
        "teh_bahawalpur-saddar": "Bahawalpur Saddar",
        "teh_bhakkar": "Bhakkar",
        "teh_bhalwal": "Bhalwal",
        "teh_bhera": "Bhera",
        "teh_bhuwana": "Bhuwana",
        "teh_burewala": "Burewala",
        "teh_chak-jhumra": "Chak Jhumra",
        "teh_chakwal": "Chakwal",
        "teh_chaubara": "Chaubara",
        "teh_chichawatni": "Chichawatni",
        "teh_chiniot": "Chiniot",
        "teh_chishtian": "Chishtian",
        "teh_choa-saidan-shah": "Choa Saidan Shah",
        "teh_chowk-sarwar-shaheed": "Chowk Sarwar Shaheed",
        "teh_chunian": "Chunian",
        "teh_darya-khan": "Darya Khan",
        "teh_daska": "Daska",
        "teh_daultala": "Daultala",
        "teh_de-excluded-area-rajanpur": "De-Excluded Area Rajanpur",
        "teh_depalpur": "Depalpur",
        "teh_dera-ghazi-khan": "Dera Ghazi Khan",
        "teh_dina": "Dina",
        "teh_dunyapur": "Dunyapur",
        "teh_faisalabad-city": "Faisalabad City",
        "teh_faisalabad-saddar": "Faisalabad Saddar",
        "teh_fateh-jang": "Fateh Jang",
        "teh_ferozewala": "Ferozewala",
        "teh_fort-abbas": "Fort Abbas",
        "teh_gojra": "Gojra",
        "teh_gujar-khan": "Gujar Khan",
        "teh_gujranwala-city": "Gujranwala City",
        "teh_gujranwala-saddar": "Gujranwala Saddar",
        "teh_gujrat": "Gujrat",
        "teh_hafizabad": "Hafizabad",
        "teh_haroonabad": "Haroonabad",
        "teh_hasilpur": "Hasilpur",
        "teh_hassan-abdal": "Hassan Abdal",
        "teh_hazro": "Hazro",
        "teh_isakhel": "Isakhel",
        "teh_jahanian": "Jahanian",
        "teh_jalalpur-jattan": "Jalalpur Jattan",
        "teh_jalalpur-pirwala": "Jalalpur Pirwala",
        "teh_jallah-jeem": "Jallah Jeem",
        "teh_jand": "Jand",
        "teh_jaranwala": "Jaranwala",
        "teh_jatoi": "Jatoi",
        "teh_jhang": "Jhang",
        "teh_jhelum": "Jhelum",
        "teh_kabirwala": "Kabirwala",
        "teh_kahror-pacca": "Kahror Pacca",
        "teh_kahuta": "Kahuta",
        "teh_kallar-kahar": "Kallar Kahar",
        "teh_kallar-syedan": "Kallar Syedan",
        "teh_kaloorkot": "Kaloorkot",
        "teh_kamalia": "Kamalia",
        "teh_kamoke": "Kamoke",
        "teh_karor-lal-esan": "Karor Lal Esan",
        "teh_kasur": "Kasur",
        "teh_khairpur-tamewali": "Khairpur Tamewali",
        "teh_khanewal": "Khanewal",
        "teh_khanpur": "Khanpur",
        "teh_kharian": "Kharian",
        "teh_khushab": "Khushab",
        "teh_koh-e-suleman": "Koh-e-Suleman",
        "teh_kot-addu": "Kot Addu",
        "teh_kot-chutta": "Kot Chutta",
        "teh_kot-momin": "Kot Momin",
        "teh_kot-radha-kishan": "Kot Radha Kishan",
        "teh_kotli-sattian": "Kotli Sattian",
        "teh_kunjah": "Kunjah",
        "teh_lahore-cantt": "Lahore Cantonment",
        "teh_lahore-city": "Lahore City",
        "teh_lalian": "Lalian",
        "teh_lawa": "Lawa",
        "teh_layyah": "Layyah",
        "teh_liaqatpur": "Liaqatpur",
        "teh_lodhran": "Lodhran",
        "teh_mailsi": "Mailsi",
        "teh_malakwal": "Malakwal",
        "teh_mandi-bahauddin": "Mandi Bahauddin",
        "teh_mandi-shah-jeewna": "Mandi Shah Jeewna",
        "teh_mankera": "Mankera",
        "teh_mian-channu": "Mian Channu",
        "teh_mianwali": "Mianwali",
        "teh_minchinabad": "Minchinabad",
        "teh_model-town": "Model Town",
        "teh_multan-city": "Multan City",
        "teh_multan-khurd": "Multan Khurd",
        "teh_multan-saddar": "Multan Saddar",
        "teh_muridke": "Muridke",
        "teh_murree": "Murree",
        "teh_muzaffargarh": "Muzaffargarh",
        "teh_nankana-sahib": "Nankana Sahib",
        "teh_narowal": "Narowal",
        "teh_naushera": "Naushera (Wadi-e-Soon)",
        "teh_noorpur-thal": "Noorpur Thal",
        "teh_nowshera-virkan": "Nowshera Virkan",
        "teh_okara": "Okara",
        "teh_pakpattan": "Pakpattan",
        "teh_pasrur": "Pasrur",
        "teh_pattoki": "Pattoki",
        "teh_phalia": "Phalia",
        "teh_pind-dadan-khan": "Pind Dadan Khan",
        "teh_pindi-bhattian": "Pindi Bhattian",
        "teh_pindi-gheb": "Pindi Gheb",
        "teh_piplan": "Piplan",
        "teh_pirmahal": "Pirmahal",
        "teh_quaidabad": "Quaidabad",
        "teh_rahim-yar-khan": "Rahim Yar Khan",
        "teh_raiwind": "Raiwind",
        "teh_rajanpur": "Rajanpur",
        "teh_rawalpindi": "Rawalpindi",
        "teh_renala-khurd": "Renala Khurd",
        "teh_rojhan": "Rojhan",
        "teh_sadiqabad": "Sadiqabad",
        "teh_safdarabad": "Safdarabad",
        "teh_sahiwal": "Sahiwal",
        "teh_sambrial": "Sambrial",
        "teh_samundri": "Samundri",
        "teh_sangla-hill": "Sangla Hill",
        "teh_sarai-alamgir": "Sarai Alamgir",
        "teh_sargodha": "Sargodha",
        "teh_shah-kot": "Shah Kot",
        "teh_shahpur": "Shahpur",
        "teh_shakargarh": "Shakargarh",
        "teh_shalimar": "Shalimar",
        "teh_sharaqpur": "Sharaqpur",
        "teh_sheikhupura": "Sheikhupura",
        "teh_shorkot": "Shorkot",
        "teh_shujabad": "Shujabad",
        "teh_sialkot": "Sialkot",
        "teh_sillanwali": "Sillanwali",
        "teh_sohawa": "Sohawa",
        "teh_talagang": "Talagang",
        "teh_tandlianwala": "Tandlianwala",
        "teh_taunsa": "Taunsa",
        "teh_taxila": "Taxila",
        "teh_toba-tek-singh": "Toba Tek Singh",
        "teh_vehari": "Vehari",
        "teh_wahova": "Wahova",
        "teh_wazirabad": "Wazirabad",
        "teh_yazman": "Yazman",
        "teh_zafarwal": "Zafarwal",
        "tehsil": "Tehsil",
    },
}
